[package]
name = "wedge"
version = "0.2.0"
edition = "2018"
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
license = "Apache-2.0"

[dependencies]
paste = "1.0.5"
thiserror = "1.0.26"
wasmedge-sys = { path = "../wasmedge-sys" }
