[package]
categories = ["api-bindings", "wasm"]
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
documentation = "https://wasmedge.github.io/WasmEdge/wasmedge_sdk/"
edition = "2021"
exclude = ["examples/"]
license = "Apache-2.0"
name = "wasmedge-sdk"
readme = "README.md"
repository = "https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sdk"
version = "0.6.0"

[dependencies]
anyhow = "1.0"
thiserror = "1.0.30"
wasmedge-macro = {path = "../wasmedge-macro", version = "0.2"}
wasmedge-sys = {path = "../wasmedge-sys", version = "0.11", default-features = false}
wasmedge-types = {path = "../wasmedge-types", version = "0.3"}
wat = "1.0"

[features]
aot = ["wasmedge-sys/aot"]
default = ["aot"]
wasi_crypto = ["wasmedge-sys/wasi_crypto"]
wasi_nn = ["wasmedge-sys/wasi_nn"]

[dev-dependencies]
tokio = {version = "1", features = ["full"]}
