[package]
name = "wasmedge"
version = "0.1.0"
edition = "2021"
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/crate/wasmedge-sdk"
repository = "https://github.com/WasmEdge/WasmEdge/bindings/rust/wasmedge"
categories = ["api-bindings", "wasm"]
exclude = ["examples/"]

[dependencies]
wasmedge-sys = { path = "../wasmedge-sys", version="0.7" }
thiserror = "1.0.30"
wasmedge-types = "0.1.1"
wat = "1.0"
anyhow = "1.0"

[features]
default = ["aot"]
aot = []
