[package]
categories = ["data-structures"]
description = "The common data structures for WasmEdge Rust bindings."
documentation = "https://wasmedge.github.io/WasmEdge/wasmedge_types/"
edition = "2021"
license = "Apache-2.0"
name = "wasmedge-types"
readme = "README.md"
repository = "https://github.com/WasmEdge/WasmEdge/tree/master/bindings/rust/wasmedge-types"
version = "0.4.0"

[dependencies]
thiserror = "1.0.30"
wat = "1.0"
