site_name: WasmEdge PySDK
site_author: Shreyas Atre
site_description: "Documentation for Python SDK for WasmEdge"

repo_url: https://github.com/WasmEdge/WasmEdge

theme: 
  name : material
  features:
        - tabs
  palette:
    scheme: preference
nav:
    - Home: index.md
    - Commands: commands/commands.md
    - Development: development/development.md
    - History: HISTORY.md

markdown_extensions:
  - admonition
  - codehilite    
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.arithmatex