[package]
build = "build.rs"
categories = ["api-bindings", "wasm"]
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
documentation = "https://wasmedge.github.io/WasmEdge/wasmedge_sys/"
edition = "2021"
exclude = ["tests/", "examples/"]
license = "Apache-2.0"
links = "wasmedge"
name = "wasmedge-sys"
readme = "README.md"
repository = "https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys"
version = "0.13.0"

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.94"
parking_lot = "0.12.1"
paste = "1.0.5"
rand = "0.8.4"
thiserror = "1.0.30"
wasmedge-macro = {path = "../wasmedge-macro", version = "0.3"}
wasmedge-types = {path = "../wasmedge-types", version = "0.4"}
wasmtime-fiber = {version = "6", optional = true}
wat = "1.0"

[build-dependencies]
bindgen = {version = "0.61", default-features = false, features = ["runtime"]}
cmake = "0.1"

[dev-dependencies]
anyhow = "1"
tokio = {version = "1", features = ["full"]}

[features]
aot = []
async = ["wasmtime-fiber"]
default = []
ffi = []
standalone = []
static = []
wasi_crypto = []
wasi_nn = []
wasmedge_process = []
