name: Clang-Format

concurrency:
  group: clang-format-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install clang-format-12
      run: |
        apt update
        apt install clang-format-12
    - name: Run clang-format
      run: |
        bash ./.github/scripts/clang-format.sh `which clang-format-12`
    - name: Run header check
      run: |
        apt update
        apt install python -y
        python ./.github/scripts/conf-header.py

