name: Build on manylinux

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      matrix: # [ { name, runner, docker_tag }, ... ]
        type: string
        required: true
      release:
        type: boolean

permissions:
  contents: read

jobs:
  build_on_manylinux:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.matrix) }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    container: wasmedge/wasmedge:${{ matrix.docker_tag }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Build ${{ matrix.asset_tag }} package
        run: |
          bash utils/docker/build-manylinux.sh -DWASMEDGE_USE_CXX11_ABI=OFF
          ./build/tools/wasmedge/wasmedge -v
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          path: build/WasmEdge-${{ inputs.version }}-Linux.tar.gz
          name: WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.tar.gz
      - name: Install gh
        if: ${{ inputs.release }}
        run: |
          echo "Detected docker tag: ${{ matrix.docker_tag }}"
          type -p yum-config-manager >/dev/null || yum install -y yum-utils
          yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          yum install -y gh
      - name: Upload rpm package
        if: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv build/WasmEdge-${{ inputs.version }}-Linux.rpm WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.rpm
          gh release upload ${{ inputs.version }} WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.rpm --clobber
      - name: Upload tar.gz package
        if: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv build/WasmEdge-${{ inputs.version }}-Linux.tar.gz WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.tar.gz
          gh release upload ${{ inputs.version }} WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.tar.gz --clobber
      - name: Upload tar.xz package
        if: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv build/WasmEdge-${{ inputs.version }}-Linux.tar.xz WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.tar.xz
          gh release upload ${{ inputs.version }} WasmEdge-${{ inputs.version }}-${{ matrix.asset_tag }}.tar.xz --clobber
