name: wasmedge-sdk-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-20.04
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up build environment
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev ninja-build
          apt install -y llvm-12-dev liblld-12-dev

      - name: Install Rust v1.65
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.65
          components: rustfmt, clippy

      - name: Build WasmEdge with Release mode
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON .
          cmake --build build

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          cargo publish --dry-run -p wasmedge-sdk

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          cargo publish -p wasmedge-sdk

      - name: Build API document
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../../build/plugins/wasmedge_process"
          export LD_LIBRARY_PATH="$(pwd)/../../../build/lib/api"
          cargo doc -p wasmedge-sdk --workspace --no-deps --features aot,async,wasi_crypto,wasi_nn --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-sdk/target/doc
          force_orphan: true
