name: wasmedge-sdk crate release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
      - "rust/*"
    tags:
      - "rust-sdk/[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build WasmEdge with Release mode
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-12-dev liblld-12-dev ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON .
          cmake --build build

      - name: Publish wasmedge-sdk crate
        if: github.ref_type == 'tag'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        run: |
          cd bindings/rust/
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          git config --global user.email "runner@gha.local"
          git config --global user.name "Github Action"
          cargo publish -p wasmedge-sdk --dry-run
          cargo publish -p wasmedge-sdk

      - name: Dry run wasmedge-sdk crate
        if: github.ref_type == 'branch'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        run: |
          cd bindings/rust/
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          git config --global user.email "runner@gha.local"
          git config --global user.name "Github Action"
          cargo publish -p wasmedge-sdk --dry-run
