name: wasmedge-types-docs

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
      - "release/rust-types/*"
    paths:
      - ".github/workflows/rust-wasmedge-types-docs.yml"
      - "bindings/rust/wasmedge-types/**"
    tags:
      - "rust-types/[0-9]+.[0-9]+.[0-9]+*"

jobs:
  rustdoc:
    name: rustdoc
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build WasmEdge with Release mode
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-12-dev liblld-12-dev ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON .
          cmake --build build

      - name: Build Documentation
        run: |
          cd bindings/rust/wasmedge-types
          export WASMEDGE_DIR="$(pwd)/../../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../../build/plugins/wasmedge_process"
          export LD_LIBRARY_PATH="$(pwd)/../../../build/lib/api"
          cargo doc --all --no-deps --target-dir=./target

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-types/target/doc
          force_orphan: true
