name: wasmedge-sdk crate release

concurrency:
  group: wasmedge-sdk-crate-release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "rust-sdk/[0-9]+.[0-9]+.[0-9]+*"

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build WasmEdge using clang
        run: |
          cmake -Bbuild -GNinja -DWASMEDGE_BUILD_SHARED_LIB=ON  -DCMAKE_INSTALL_PREFIX:PATH=/usr .
          cmake --build build --target install

      - name: Publish wasmedge-sdk crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        run: |
          cd bindings/rust/wasmedge-sdk
          git config --global user.email "runner@gha.local"
          git config --global user.name "Github Action"
          cargo publish --dry-run
          cargo publish
