name: Test Wasi Testsuite

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/wasi-testsuite.yml"
      - "lib/host/wasi/**"
      - "include/host/wasi/**"
      - "thirdparty/wasi/**"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/wasi-testsuite.yml"
      - "lib/host/wasi/**"
      - "include/host/wasi/**"
      - "thirdparty/wasi/**"

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: WasmEdge
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Build WasmEdge on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        working-directory: WasmEdge
        run: |
          sudo apt install -y software-properties-common cmake clang ninja-build
          cmake -Bbuild -GNinja -DWASMEDGE_USE_LLVM=OFF .
          cmake --build build
          echo "$GITHUB_WORKSPACE/WasmEdge/build/tools/wasmedge" >> $GITHUB_PATH

      - name: Build WasmEdge on macOS
        if: matrix.os == 'macos-latest'
        working-directory: WasmEdge
        run: |
          brew install llvm ninja
          # cmake is installed by local/pinned tap inside the macos runner image
          export LLVM_DIR="/usr/local/opt/llvm/lib/cmake"
          export CC=clang
          export CXX=clang++
          cmake -Bbuild -GNinja -DWASMEDGE_USE_LLVM=OFF .
          cmake --build build
          echo "$GITHUB_WORKSPACE/WasmEdge/build/tools/wasmedge" >> $GITHUB_PATH

      - name: Install dependency on Windows
        if: matrix.os == 'windows-2025'
        uses: crazy-max/ghaction-chocolatey@2526f467ccbd337d307fe179959cabbeca0bc8c0 # v3.4.0
        with:
          args: install --no-progress ninja vswhere
      - name: Upgrade dependency on Windows
        if: matrix.os == 'windows-2025'
        uses: crazy-max/ghaction-chocolatey@2526f467ccbd337d307fe179959cabbeca0bc8c0 # v3.4.0
        with:
          args: upgrade --no-progress llvm
      - name: Install Windows SDK
        if: matrix.os == 'windows-2025'
        uses: GuillaumeFalourd/setup-windows10-sdk-action@9979bedbf6ae74f038cc338622ba015942ed2408 # v2.4
        with:
          sdk-version: 26100
      - name: Build WasmEdge on Windows
        if: matrix.os == 'windows-2025'
        working-directory: WasmEdge
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath Common7\Tools\Microsoft.VisualStudio.DevShell.dll)
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.26100.0"
          $uri = "https://github.com/WasmEdge/llvm-windows/releases/download/llvmorg-21.1.3/LLVM-21.1.3-win64-MultiThreadedDLL.zip"
          $llvm = "LLVM-21.1.3-win64-MultiThreadedDLL.zip"
          Invoke-WebRequest -Uri $uri -HttpVersion 2.0 -OutFile $llvm
          Expand-Archive -Path $llvm
          $Env:CC = "$pwd\LLVM-21.1.3-win64-MultiThreadedDLL\LLVM-21.1.3-win64\bin\clang-cl.exe"
          $Env:CXX = "$pwd\LLVM-21.1.3-win64-MultiThreadedDLL\LLVM-21.1.3-win64\bin\clang-cl.exe"
          $llvm_mt = "mt"
          $cmake_sys_version = "10.0.26100.0"
          cmake -Bbuild -GNinja -DCMAKE_SYSTEM_VERSION="$cmake_sys_version" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL -DCMAKE_MT="$llvm_mt" -DWASMEDGE_USE_LLVM=OFF .
          cmake --build build
          echo "$Env:GITHUB_WORKSPACE\\WasmEdge\\build\\tools\\wasmedge" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          echo "$Env:GITHUB_WORKSPACE\\WasmEdge\\build\\lib\\api" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout wasi-testsuite
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: WebAssembly/wasi-testsuite
          ref: prod/testsuite-base
          path: wasi-testsuite

      - name: Initialize Python environment
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
          cache: pip

      - name: Install wasi testsuite dependencies
        working-directory: wasi-testsuite/test-runner
        run: pip install -r requirements.txt

      - name: Test Wasi testsuite
        working-directory: wasi-testsuite
        run: python3 test-runner/wasi_test_runner.py -t ./tests/assemblyscript/testsuite/ ./tests/c/testsuite/ ./tests/rust/testsuite/ -r ../WasmEdge/.github/scripts/wasi-testsuite-adapter.py
